/**
 * 2026 Regulatory Requirements - Sample Data
 *
 * This file contains sample requirement definitions for 2026-specific regulations:
 * 1. EU AI Act - AI transparency and governance
 * 2. HIPAA 2026 Updates - Enhanced MFA and encryption
 * 3. Post-Quantum Cryptography - NIST PQC standards
 * 4. Zero Trust - Continuous verification requirements
 */

import type {
  AIActRequirement,
  QuantumReadinessRequirement,
  ZeroTrustRequirement,
  FrameworkVersion,
} from '../types/regulatory-update.types';

// ============================================
// FRAMEWORK VERSIONS - 2026
// ============================================

export const FRAMEWORK_VERSIONS_2026: FrameworkVersion[] = [
  {
    id: 'eu_ai_act_2024',
    frameworkId: 'EU_AI_ACT',
    versionCode: '2024',
    versionName: 'EU AI Act - Initial Implementation',
    status: 'active',
    publishedDate: '2024-07-12',
    effectiveDate: '2024-08-01',
    transitionDeadline: '2026-08-01',
    officialSource: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
    sourceLastChecked: new Date().toISOString(),
    majorChanges: [],
    jurisdiction: ['EU', 'EEA'],
    applicableSectors: ['All'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'hipaa_2026_update',
    frameworkId: 'HIPAA',
    versionCode: '2026-update',
    versionName: 'HIPAA Security Rule 2026 Update',
    status: 'published',
    publishedDate: '2025-12-01',
    effectiveDate: '2026-06-01',
    transitionDeadline: '2027-06-01',
    officialSource: 'https://www.hhs.gov/hipaa/for-professionals/security/index.html',
    sourceLastChecked: new Date().toISOString(),
    previousVersionId: 'hipaa_2013',
    changelogSummary: 'Mandatory MFA, enhanced encryption requirements, and zero trust alignment',
    majorChanges: [
      {
        id: 'hipaa-2026-mfa',
        changeType: 'strengthened',
        affectedRequirementCode: '164.312(d)',
        previousText: 'Implement procedures to verify identity of person seeking access',
        newText: 'Implement phishing-resistant multi-factor authentication for all users accessing ePHI',
        impactLevel: 'critical',
        complianceImpact: 'Organizations must implement phishing-resistant MFA within 12 months',
        actionRequired: 'Deploy FIDO2/WebAuthn or similar phishing-resistant MFA',
        affectedControlIds: ['MFA-01', 'AC-001', 'AC-002'],
        tags: ['mfa', 'authentication', 'zero-trust'],
      },
      {
        id: 'hipaa-2026-encryption',
        changeType: 'strengthened',
        affectedRequirementCode: '164.312(a)(2)(iv)',
        previousText: 'Implement mechanism to encrypt ePHI (addressable)',
        newText: 'Encryption of ePHI is mandatory. Organizations must use AES-256 or NIST-approved post-quantum algorithms',
        impactLevel: 'critical',
        complianceImpact: 'Encryption is no longer addressable - it is mandatory',
        actionRequired: 'Ensure all ePHI is encrypted with AES-256 minimum',
        affectedControlIds: ['ENC-001', 'ENC-002', 'DP-001'],
        tags: ['encryption', 'data-protection', 'quantum-readiness'],
      },
    ],
    jurisdiction: ['US'],
    applicableSectors: ['Healthcare'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'nist_pqc_2025',
    frameworkId: 'NIST',
    versionCode: 'PQC-2025',
    versionName: 'NIST Post-Quantum Cryptography Standards',
    status: 'published',
    publishedDate: '2024-08-13',
    effectiveDate: '2025-01-01',
    transitionDeadline: '2030-12-31',
    officialSource: 'https://csrc.nist.gov/projects/post-quantum-cryptography',
    sourceLastChecked: new Date().toISOString(),
    changelogSummary: 'Standardization of ML-KEM, ML-DSA, and SLH-DSA algorithms',
    majorChanges: [
      {
        id: 'nist-pqc-kem',
        changeType: 'added',
        affectedRequirementCode: 'PQC-KEM-001',
        newText: 'Organizations handling sensitive data must implement ML-KEM (FIPS 203) for key encapsulation',
        impactLevel: 'high',
        complianceImpact: 'New key encapsulation requirements for long-term data protection',
        actionRequired: 'Begin cryptographic inventory and migration planning',
        affectedControlIds: ['CRYPTO-001', 'CRYPTO-002'],
        tags: ['post-quantum', 'encryption', 'key-management'],
      },
    ],
    jurisdiction: ['US', 'Global'],
    applicableSectors: ['All'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ============================================
// EU AI ACT REQUIREMENTS
// ============================================

export const EU_AI_ACT_REQUIREMENTS: AIActRequirement[] = [
  {
    id: 'AI-ACT-ART-52-1',
    frameworkId: 'EU_AI_ACT',
    frameworkVersionId: 'eu_ai_act_2024',
    requirementCode: 'Art. 52(1)',
    hierarchy: ['Title IV', 'Chapter 2', 'Article 52', 'Paragraph 1'],
    title: 'AI System Transparency - User Notification',
    officialText: 'Providers shall ensure that AI systems intended to interact with natural persons are designed and developed in such a way that natural persons are informed that they are interacting with an AI system, unless this is obvious from the circumstances and the context of use.',
    plainLanguageSummary: 'Users must be clearly informed when they are interacting with an AI system (chatbots, virtual assistants, etc.)',
    implementationGuidance: 'Implement clear disclosure mechanisms at the start of any AI interaction. This can include visual indicators, audio announcements, or explicit text notifications.',
    category: 'ai_transparency',
    domain: 'ai_ml_governance',
    emergingTechCategory: 'ai_general_purpose',
    implementationLevel: 'mandatory',
    riskWeight: 7,
    penaltyRisk: {
      maxFinancialPenalty: '3% of global annual turnover',
      penaltyType: 'percentage_revenue',
      criminalLiability: false,
      reputationalImpact: 'high',
    },
    requiredEvidenceTypes: ['policy_document', 'screenshot', 'test_results'],
    verificationMethods: ['documentation_review', 'technical_testing', 'observation'],
    verificationFrequency: 'continuous',
    keywords: ['ai', 'transparency', 'disclosure', 'chatbot', 'virtual assistant', 'notification'],
    effectiveDate: '2025-08-02',
    transitionPeriodDays: 365,
    sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
    lastVerifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    aiRiskLevel: 'limited',
    transparencyRequirements: {
      disclosureRequired: true,
      humanOversightRequired: false,
      explainabilityLevel: 'outcome_only',
    },
    conformityAssessment: 'self_assessment',
  },
  {
    id: 'AI-ACT-ART-9-1',
    frameworkId: 'EU_AI_ACT',
    frameworkVersionId: 'eu_ai_act_2024',
    requirementCode: 'Art. 9(1)',
    hierarchy: ['Title III', 'Chapter 2', 'Article 9', 'Paragraph 1'],
    title: 'Risk Management System for High-Risk AI',
    officialText: 'A risk management system shall be established, implemented, documented and maintained in relation to high-risk AI systems.',
    plainLanguageSummary: 'High-risk AI systems require a formal risk management system covering the entire AI lifecycle.',
    implementationGuidance: 'Establish a documented risk management framework that identifies, analyzes, estimates, and evaluates risks throughout the AI system lifecycle.',
    category: 'ai_governance',
    domain: 'ai_ml_governance',
    emergingTechCategory: 'ai_high_risk_systems',
    implementationLevel: 'mandatory',
    conditions: [
      {
        type: 'risk_level',
        operator: 'equals',
        value: 'high',
        description: 'Applies only to high-risk AI systems as defined in Annex III',
      },
    ],
    riskWeight: 9,
    penaltyRisk: {
      maxFinancialPenalty: '3% of global annual turnover or €15M',
      penaltyType: 'percentage_revenue',
      criminalLiability: false,
      reputationalImpact: 'critical',
    },
    requiredEvidenceTypes: ['risk_assessment', 'policy_document', 'procedure_document', 'audit_log'],
    verificationMethods: ['documentation_review', 'interview', 'model_audit'],
    verificationFrequency: 'continuous',
    keywords: ['risk management', 'high-risk ai', 'lifecycle', 'documentation', 'assessment'],
    effectiveDate: '2026-08-02',
    transitionPeriodDays: 365,
    sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
    lastVerifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    aiRiskLevel: 'high',
    transparencyRequirements: {
      disclosureRequired: true,
      humanOversightRequired: true,
      explainabilityLevel: 'full',
    },
    conformityAssessment: 'third_party',
  },
  {
    id: 'AI-ACT-ART-10-1',
    frameworkId: 'EU_AI_ACT',
    frameworkVersionId: 'eu_ai_act_2024',
    requirementCode: 'Art. 10(1)',
    hierarchy: ['Title III', 'Chapter 2', 'Article 10', 'Paragraph 1'],
    title: 'Training Data Governance',
    officialText: 'High-risk AI systems which make use of techniques involving the training of models with data shall be developed on the basis of training, validation and testing data sets that meet the quality criteria referred to in paragraphs 2 to 5.',
    plainLanguageSummary: 'Training data for high-risk AI must meet strict quality standards including relevance, representativeness, and freedom from errors.',
    implementationGuidance: 'Implement data governance practices including data quality checks, bias assessments, representativeness analysis, and documentation of data sources.',
    category: 'ai_bias_mitigation',
    domain: 'ai_ml_governance',
    emergingTechCategory: 'ai_high_risk_systems',
    implementationLevel: 'mandatory',
    conditions: [
      {
        type: 'risk_level',
        operator: 'equals',
        value: 'high',
        description: 'Applies only to high-risk AI systems',
      },
      {
        type: 'technology',
        operator: 'equals',
        value: 'ml_training',
        description: 'Applies only to AI systems trained on data',
      },
    ],
    riskWeight: 9,
    penaltyRisk: {
      maxFinancialPenalty: '3% of global annual turnover or €15M',
      penaltyType: 'percentage_revenue',
      criminalLiability: false,
      reputationalImpact: 'critical',
    },
    requiredEvidenceTypes: ['policy_document', 'test_results', 'audit_log'],
    verificationMethods: ['documentation_review', 'bias_assessment', 'model_audit'],
    verificationFrequency: 'on_change',
    keywords: ['training data', 'data quality', 'bias', 'representativeness', 'data governance'],
    effectiveDate: '2026-08-02',
    transitionPeriodDays: 365,
    sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
    lastVerifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    aiRiskLevel: 'high',
    dataGovernance: {
      dataQualityStandards: ['relevance', 'representativeness', 'error-free', 'completeness'],
      biasAssessmentRequired: true,
      dataProvenanceRequired: true,
      syntheticDataRules: 'Synthetic data must meet same quality criteria as real data',
    },
    conformityAssessment: 'third_party',
  },
];

// ============================================
// POST-QUANTUM CRYPTOGRAPHY REQUIREMENTS
// ============================================

export const PQC_REQUIREMENTS: QuantumReadinessRequirement[] = [
  {
    id: 'NIST-PQC-INVENTORY',
    frameworkId: 'NIST',
    frameworkVersionId: 'nist_pqc_2025',
    requirementCode: 'PQC-INV-001',
    hierarchy: ['Post-Quantum Cryptography', 'Inventory Requirements'],
    title: 'Cryptographic Asset Inventory',
    officialText: 'Organizations shall maintain a comprehensive inventory of all cryptographic assets, including algorithms, key sizes, and their locations within systems and applications.',
    plainLanguageSummary: 'You must know what cryptography you use and where. Create a complete inventory of all encryption, digital signatures, and key exchange mechanisms.',
    implementationGuidance: 'Deploy cryptographic discovery tools, audit code repositories for crypto usage, document all TLS/SSL configurations, and maintain a living inventory document.',
    category: 'quantum_readiness',
    domain: 'cryptographic_controls',
    emergingTechCategory: 'post_quantum_crypto',
    implementationLevel: 'mandatory',
    riskWeight: 8,
    penaltyRisk: {
      maxFinancialPenalty: 'Varies by sector',
      penaltyType: 'per_violation',
      criminalLiability: false,
      reputationalImpact: 'high',
    },
    requiredEvidenceTypes: ['configuration_export', 'audit_log', 'policy_document'],
    verificationMethods: ['documentation_review', 'automated_scan', 'technical_testing'],
    verificationFrequency: 'quarterly',
    keywords: ['cryptographic inventory', 'crypto assets', 'encryption', 'key management', 'pqc'],
    effectiveDate: '2025-01-01',
    transitionPeriodDays: 365,
    sourceUrl: 'https://csrc.nist.gov/projects/post-quantum-cryptography',
    lastVerifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    quantumThreatLevel: 'near_term',
    cryptoRequirements: {
      currentAlgorithms: ['RSA-2048', 'ECDSA', 'ECDH', 'DH'],
      approvedPQCAlgorithms: ['ML-KEM-768', 'ML-KEM-1024', 'ML-DSA-65', 'ML-DSA-87', 'SLH-DSA-128s'],
      hybridApproach: true,
      migrationDeadline: '2030-12-31',
    },
  },
  {
    id: 'NIST-PQC-KEM',
    frameworkId: 'NIST',
    frameworkVersionId: 'nist_pqc_2025',
    requirementCode: 'PQC-KEM-001',
    hierarchy: ['Post-Quantum Cryptography', 'Key Encapsulation'],
    title: 'Post-Quantum Key Encapsulation',
    officialText: 'For data requiring protection beyond 2030, organizations shall implement FIPS 203 (ML-KEM) compliant key encapsulation mechanisms, either as a replacement or in hybrid mode with existing algorithms.',
    plainLanguageSummary: 'For sensitive long-term data, start using quantum-resistant key exchange (ML-KEM/Kyber) alongside or instead of current methods like RSA or ECDH.',
    implementationGuidance: 'Prioritize systems handling data with long-term secrecy requirements. Implement hybrid TLS using ML-KEM + X25519. Update key management infrastructure.',
    category: 'quantum_readiness',
    domain: 'cryptographic_controls',
    emergingTechCategory: 'post_quantum_crypto',
    implementationLevel: 'recommended',
    conditions: [
      {
        type: 'data_type',
        operator: 'in_list',
        value: ['classified', 'healthcare', 'financial', 'pii'],
        description: 'Required for data needing protection beyond 2030',
      },
    ],
    riskWeight: 8,
    penaltyRisk: {
      maxFinancialPenalty: 'Varies by sector',
      penaltyType: 'per_violation',
      criminalLiability: false,
      reputationalImpact: 'high',
    },
    requiredEvidenceTypes: ['configuration_export', 'test_results', 'certificate'],
    verificationMethods: ['technical_testing', 'automated_scan', 'code_review'],
    verificationFrequency: 'on_change',
    keywords: ['ml-kem', 'kyber', 'key encapsulation', 'hybrid cryptography', 'tls', 'pqc'],
    effectiveDate: '2025-01-01',
    transitionPeriodDays: 1825, // 5 years
    sourceUrl: 'https://csrc.nist.gov/pubs/fips/203/final',
    lastVerifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    quantumThreatLevel: 'medium_term',
    cryptoRequirements: {
      currentAlgorithms: ['RSA-2048', 'ECDH-P256', 'X25519'],
      approvedPQCAlgorithms: ['ML-KEM-768', 'ML-KEM-1024'],
      hybridApproach: true,
      migrationDeadline: '2030-12-31',
    },
    keyManagement: {
      keyLengthRequirements: { 'ML-KEM': 768, 'AES': 256 },
      keyRotationFrequency: 'annual',
      harvestNowDecryptLater: true,
    },
    dataQuantumRisk: {
      longTermSecrecy: true,
      sensitivityLevel: 'confidential',
    },
  },
];

// ============================================
// ZERO TRUST REQUIREMENTS (HIPAA 2026)
// ============================================

export const ZERO_TRUST_REQUIREMENTS: ZeroTrustRequirement[] = [
  {
    id: 'HIPAA-2026-MFA',
    frameworkId: 'HIPAA',
    frameworkVersionId: 'hipaa_2026_update',
    requirementCode: '164.312(d)-2026',
    hierarchy: ['Security Rule', 'Technical Safeguards', 'Person or Entity Authentication'],
    title: 'Phishing-Resistant Multi-Factor Authentication',
    officialText: 'Covered entities must implement phishing-resistant multi-factor authentication for all workforce members accessing electronic protected health information (ePHI).',
    plainLanguageSummary: 'All users accessing ePHI must use phishing-resistant MFA (like FIDO2 security keys or biometrics), not just passwords or SMS codes.',
    implementationGuidance: 'Deploy FIDO2-compliant authenticators (hardware keys or platform authenticators). Disable weaker MFA methods like SMS or email OTP for ePHI access.',
    category: 'zero_trust',
    domain: 'identity_governance',
    emergingTechCategory: 'zero_trust_architecture',
    implementationLevel: 'mandatory',
    riskWeight: 10,
    penaltyRisk: {
      maxFinancialPenalty: '$1.5M per violation category',
      penaltyType: 'per_violation',
      criminalLiability: true,
      reputationalImpact: 'critical',
    },
    requiredEvidenceTypes: ['configuration_export', 'screenshot', 'policy_document', 'test_results'],
    verificationMethods: ['technical_testing', 'documentation_review', 'observation'],
    verificationFrequency: 'continuous',
    keywords: ['mfa', 'fido2', 'webauthn', 'phishing-resistant', 'authentication', 'zero-trust'],
    effectiveDate: '2026-06-01',
    transitionPeriodDays: 365,
    sourceUrl: 'https://www.hhs.gov/hipaa/for-professionals/security/index.html',
    lastVerifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    zeroTrustPillar: 'identity',
    identityRequirements: {
      mfaRequired: true,
      mfaStrength: 'phishing_resistant',
      continuousAuthentication: false,
      riskBasedAccess: true,
      sessionTimeout: 15,
    },
  },
  {
    id: 'HIPAA-2026-CONTINUOUS-AUTH',
    frameworkId: 'HIPAA',
    frameworkVersionId: 'hipaa_2026_update',
    requirementCode: '164.312(d)(2)-2026',
    hierarchy: ['Security Rule', 'Technical Safeguards', 'Continuous Verification'],
    title: 'Continuous Identity Verification',
    officialText: 'Covered entities shall implement mechanisms for continuous or periodic re-verification of user identity during active sessions accessing ePHI, based on risk level.',
    plainLanguageSummary: 'Long sessions accessing patient data should periodically re-verify the user is still who they claim to be, especially for high-risk actions.',
    implementationGuidance: 'Implement step-up authentication for sensitive actions. Use behavioral analytics to detect anomalies. Require re-authentication for high-risk operations.',
    category: 'zero_trust',
    domain: 'identity_governance',
    emergingTechCategory: 'zero_trust_architecture',
    implementationLevel: 'mandatory',
    riskWeight: 8,
    penaltyRisk: {
      maxFinancialPenalty: '$1.5M per violation category',
      penaltyType: 'per_violation',
      criminalLiability: false,
      reputationalImpact: 'high',
    },
    requiredEvidenceTypes: ['configuration_export', 'audit_log', 'test_results'],
    verificationMethods: ['technical_testing', 'observation', 'automated_scan'],
    verificationFrequency: 'continuous',
    keywords: ['continuous authentication', 'step-up auth', 'session management', 'zero-trust', 'reauthentication'],
    effectiveDate: '2026-06-01',
    transitionPeriodDays: 365,
    sourceUrl: 'https://www.hhs.gov/hipaa/for-professionals/security/index.html',
    lastVerifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    zeroTrustPillar: 'identity',
    identityRequirements: {
      mfaRequired: true,
      mfaStrength: 'phishing_resistant',
      continuousAuthentication: true,
      riskBasedAccess: true,
      sessionTimeout: 15,
    },
  },
];

// ============================================
// SUGGESTED CONTROLS FOR 2026 REQUIREMENTS
// ============================================

export const SUGGESTED_CONTROLS_2026 = [
  // AI Act Controls
  {
    id: 'AI-CTRL-001',
    title: 'AI System Inventory and Risk Classification',
    description: 'Maintain a comprehensive inventory of all AI systems with risk classification according to EU AI Act categories.',
    question: 'Do you maintain an inventory of all AI systems with documented risk classifications?',
    guidance: 'Create an AI system register that includes: system name, purpose, risk level (unacceptable/high/limited/minimal), deployment status, and responsible owner.',
    domain: 'ai_ml_governance',
    category: 'ai_governance',
    emergingTechCategory: 'ai_high_risk_systems',
    keywords: ['ai inventory', 'risk classification', 'ai governance', 'eu ai act'],
    requiredEvidenceTypes: ['policy_document', 'audit_log'],
    effort: 'medium',
    impact: 'high',
    riskLevel: 'high',
  },
  {
    id: 'AI-CTRL-002',
    title: 'AI Transparency Disclosure',
    description: 'Ensure all user-facing AI systems clearly disclose that users are interacting with AI.',
    question: 'Do your AI systems clearly inform users that they are interacting with AI?',
    guidance: 'Implement disclosure mechanisms at the start of AI interactions. Include visual indicators, audio announcements, or explicit text for chatbots and virtual assistants.',
    domain: 'ai_ml_governance',
    category: 'ai_transparency',
    emergingTechCategory: 'ai_general_purpose',
    keywords: ['ai transparency', 'disclosure', 'chatbot', 'user notification'],
    requiredEvidenceTypes: ['screenshot', 'test_results'],
    effort: 'low',
    impact: 'medium',
    riskLevel: 'medium',
  },
  {
    id: 'AI-CTRL-003',
    title: 'AI Training Data Governance',
    description: 'Implement data governance controls for AI training data including quality, bias assessment, and provenance tracking.',
    question: 'Do you have governance controls for AI training data including bias assessments?',
    guidance: 'Establish data quality standards, conduct regular bias assessments, document data sources and provenance, and implement data validation pipelines.',
    domain: 'ai_ml_governance',
    category: 'ai_bias_mitigation',
    emergingTechCategory: 'ai_high_risk_systems',
    keywords: ['training data', 'bias', 'data quality', 'data governance', 'provenance'],
    requiredEvidenceTypes: ['policy_document', 'test_results', 'audit_log'],
    effort: 'high',
    impact: 'high',
    riskLevel: 'critical',
  },
  // Quantum Controls
  {
    id: 'PQC-CTRL-001',
    title: 'Cryptographic Asset Inventory',
    description: 'Maintain a comprehensive inventory of all cryptographic algorithms, key sizes, and their deployment locations.',
    question: 'Do you maintain an inventory of all cryptographic assets across your systems?',
    guidance: 'Deploy crypto discovery tools, document TLS configurations, audit code for crypto usage, and maintain a living inventory of all encryption mechanisms.',
    domain: 'cryptographic_controls',
    category: 'quantum_readiness',
    emergingTechCategory: 'post_quantum_crypto',
    keywords: ['cryptographic inventory', 'encryption', 'key management', 'quantum readiness'],
    requiredEvidenceTypes: ['configuration_export', 'audit_log'],
    effort: 'medium',
    impact: 'high',
    riskLevel: 'high',
  },
  {
    id: 'PQC-CTRL-002',
    title: 'Post-Quantum Migration Planning',
    description: 'Develop and maintain a roadmap for migrating to post-quantum cryptographic algorithms.',
    question: 'Do you have a documented plan for migrating to post-quantum cryptography?',
    guidance: 'Prioritize systems by data sensitivity and longevity requirements. Plan for hybrid approaches. Set milestones aligned with NIST PQC timelines.',
    domain: 'cryptographic_controls',
    category: 'quantum_readiness',
    emergingTechCategory: 'post_quantum_crypto',
    keywords: ['pqc migration', 'quantum readiness', 'ml-kem', 'cryptographic agility'],
    requiredEvidenceTypes: ['policy_document', 'procedure_document'],
    effort: 'high',
    impact: 'high',
    riskLevel: 'high',
  },
  // Zero Trust Controls
  {
    id: 'ZT-CTRL-001',
    title: 'Phishing-Resistant MFA Deployment',
    description: 'Deploy phishing-resistant multi-factor authentication using FIDO2/WebAuthn for all sensitive system access.',
    question: 'Have you deployed phishing-resistant MFA (FIDO2/WebAuthn) for sensitive system access?',
    guidance: 'Implement hardware security keys or platform authenticators. Disable weaker MFA methods (SMS, email OTP) for sensitive systems. Train users on new authentication methods.',
    domain: 'identity_governance',
    category: 'zero_trust',
    emergingTechCategory: 'zero_trust_architecture',
    keywords: ['fido2', 'webauthn', 'phishing-resistant mfa', 'zero trust', 'authentication'],
    requiredEvidenceTypes: ['configuration_export', 'screenshot', 'test_results'],
    effort: 'medium',
    impact: 'critical',
    riskLevel: 'critical',
  },
  {
    id: 'ZT-CTRL-002',
    title: 'Continuous Identity Verification',
    description: 'Implement mechanisms for continuous or periodic re-verification of user identity during active sessions.',
    question: 'Do you implement continuous identity verification with step-up authentication for sensitive actions?',
    guidance: 'Configure adaptive authentication policies. Require re-authentication for high-risk operations. Implement behavioral analytics for anomaly detection.',
    domain: 'identity_governance',
    category: 'zero_trust',
    emergingTechCategory: 'zero_trust_architecture',
    keywords: ['continuous authentication', 'step-up auth', 'zero trust', 'adaptive authentication'],
    requiredEvidenceTypes: ['configuration_export', 'audit_log', 'test_results'],
    effort: 'high',
    impact: 'high',
    riskLevel: 'high',
  },
];
